steps:
  # Build backend image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/mt-bookclubs-backend:$SHORT_SHA', '-t', 'gcr.io/$PROJECT_ID/mt-bookclubs-backend:latest', './backend']

  # Build frontend image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/mt-bookclubs-frontend:$SHORT_SHA', '-t', 'gcr.io/$PROJECT_ID/mt-bookclubs-frontend:latest', './frontend']

  # Push backend image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/mt-bookclubs-backend:latest']

  # Push frontend image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/mt-bookclubs-frontend:latest']

  # Deploy backend to Cloud Run
  - name: 'gcr.io/cloud-builders/gke-deploy'
    args:
      - run
      - --filename=gcp/backend-cloud-run.yaml
      - --image=gcr.io/$PROJECT_ID/mt-bookclubs-backend:latest
      - --location=us-central1
      - --cluster=

  # Deploy frontend to Cloud Run
  - name: 'gcr.io/cloud-builders/gke-deploy'
    args:
      - run
      - --filename=gcp/frontend-cloud-run.yaml
      - --image=gcr.io/$PROJECT_ID/mt-bookclubs-frontend:latest
      - --location=us-central1
      - --cluster=

images:
  - 'gcr.io/$PROJECT_ID/mt-bookclubs-backend:latest'
  - 'gcr.io/$PROJECT_ID/mt-bookclubs-frontend:latest'

options:
  machineType: 'N1_HIGHCPU_8'

timeout: '1800s'
